### ISSUE TITLE
Modularize main script for scraping different years websites

### ISSUE THREAD

**Issue by josix** [pycontw/pycon_archive_past_website#16]
The script `main.py` is used for scraping PyConTW 2016-2020 websites. Currently this script contains lots of global variables and shared functions which will increase the difficulty to keep flexible for scraping the official website in the future. It is  hard to maintain/develop. It will be great if we could make this script more structural like separating different year parsing detail into different handler or module, keep the same crawling processing in a base class, etc. Any ideas about this enhancement are welcome.

**Comment by Lee-W** [comment]
In addition to that, please try [cruft](https://github.com/cruft/cruft) instead of using cookie-cutter directly. It's a tool that can help us get updates from the template easier.
